name: Publish Github Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, '[RELEASE]') }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get package version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3

      - name: Print the version
        run: echo "The version was ${{ steps.get-version.outputs.version }}"

      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
